<?php
/**
 * Страница "Содержание".
 * 
 * Английская (британская) локализация.

 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Tags Manager</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>The Tags Manager module allows you to manage website tags, allowing you to assign them to different types of content (materials, links, and other elements) to organize and simplify searching.</p>

    <h2>Content:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">List of tags</a></li>
        <li><a href="<?= $url('form') ?>">Add / Edit tag form</a></li>
    </ul>
</article>